server:
  port: 8888
  servlet:
    context-path: "/dynamic-tp"

spring:
  application:
    name: dynamic-tp-apollo-demo
  profiles:
    active: dev
  dynamic:
    tp:
      tomcatTp: # tomcat webserver线程池配置
        corePoolSize: 100
        maximumPoolSize: 200
        keepAliveTime: 60

logging:
  level:
    #root: DEBUG
    com.alibaba.nacos.client.config.impl: WARN

apollo:
  bootstrap:
    enabled: true
    namespaces: dynamic-tp-apollo-demo-dtp.yml
  meta: http://apollo.zlb.cai-inc.com
  config-service: http://apollo.zlb.cai-inc.com
app:
  id: zlb-web-mbp